# Generated by Django 3.2.3 on 2022-11-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredientunit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientunit',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_units', to='recipes.recipe'),
        ),
    ]
